### ISSUE TITLE
Rebind without having to 'press enter to chat'

### ISSUE THREAD

**Issue by Chryma** [WhatATopic/Shift-Remapping#1]
I'd like to rebind my caps lock (which is rebound to End via AHK) key to shift for all the shift actions, however when doing this it does the 'press enter to chat' thing which is not necessary since I'm not typing a key that will be typed into the game, is there any way to disable this part of the plugin?

**Comment by WhatATopic** [comment]
I'm a little confused. Rebinding caps lock to shift works fine for me. Are you saying that when you press caps lock, it starts typing in chat as if you pressed enter?

**Comment by Chryma** [comment]
Yes it does work perfectly, however it changes the way that I type in game, requiring me to hit enter before I type anything, I just mean that I want to be able to type WITHOUT hitting enter before doing so.

**Comment by WhatATopic** [comment]
Enter to chat toggle added. Thanks for the suggestion!
