### ISSUE TITLE
Remapping shift to side mouse buttons

### ISSUE THREAD

**Issue by smekisen** [WhatATopic/Shift-Remapping#2]
I can't seem to use this plugin to rebind shift to mouse4 or mouse5, is there a reason for this or just an oversight?

**Comment by WhatATopic** [comment]
Unfortunately it is a problem with Runelite's keybind system so I cannot fix it.

**Comment by WhatATopic** [comment]
Forgot this issue was still open. See here https://github.com/runelite/plugin-hub/pull/372#issuecomment-643683260
